name: algorand_hackathon
description: Decentralized Identity Solution on Algorand
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.14
  algorand_dart: ^1.0.3
  shared_preferences: ^2.2.2
  http: ^1.1.0
  qr_flutter: ^4.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true